import {
  type SubjectAggregate,
  type SubjectAggregateMembership,
  type SubjectWithProfile,
  subjectAggregateMembershipSchema,
  subjectAggregateSchema,
  subjectWithProfileSchema,
} from '@cohos/domain';

const organizationId = 'org-synthetic-cohos';

const mouseSpecies = {
  id: 'species-mus-musculus',
  commonName: 'house mouse',
  scientificName: 'Mus musculus',
  ncbiTaxonId: 'NCBITaxon:10090',
};

const zebrafishSpecies = {
  id: 'species-danio-rerio',
  commonName: 'zebrafish',
  scientificName: 'Danio rerio',
  ncbiTaxonId: 'NCBITaxon:7955',
};

const cattleSpecies = {
  id: 'species-bos-taurus',
  commonName: 'cattle',
  scientificName: 'Bos taurus',
  ncbiTaxonId: 'NCBITaxon:9913',
};

export const subjectAggregateFixtures = [
  {
    id: 'cohort-human-observational-001',
    organizationId,
    kind: 'cohort',
    code: 'COHORT-HUM-OBS-001',
    name: 'Synthetic pseudonymized human observational cohort',
    description: 'Pseudonymized human participant cohort fixture.',
    profileTypes: ['human'],
    status: 'active',
    validFrom: '2026-01-01',
    subjectIds: ['subject-human-pseudo-001'],
    cohort: {
      cohortKind: 'observational',
      studyId: 'study-synthetic-001',
      inclusionCriteria: ['Consented pseudonymized participant'],
      exclusionCriteria: ['Withdrawn consent'],
      recruitmentSource: 'Synthetic registry',
      plannedSize: 24,
      followUpSchedule: ['baseline', 'month 3'],
    },
  },
  {
    id: 'batch-rodent-shipment-001',
    organizationId,
    kind: 'batch',
    code: 'BATCH-ROD-SHIP-001',
    name: 'Synthetic rodent shipment batch',
    profileTypes: ['rodent'],
    speciesId: mouseSpecies.id,
    status: 'active',
    validFrom: '2026-02-15',
    subjectIds: ['subject-rodent-001'],
    batch: {
      originType: 'shipment',
      sourceOrganization: 'Synthetic vendor',
      strainId: 'strain-mouse-synthetic-a',
      genotypeId: 'genotype-wildtype-synthetic',
      arrivalDate: '2026-02-15',
      sexComposition: 'female',
      initialCount: 12,
      currentCount: 12,
      countUnit: 'animals',
    },
  },
  {
    id: 'group-rodent-cage-a1',
    organizationId,
    kind: 'group',
    code: 'GROUP-ROD-CAGE-A1',
    name: 'Synthetic rodent cage group A1',
    profileTypes: ['rodent'],
    speciesId: mouseSpecies.id,
    status: 'active',
    validFrom: '2026-02-16',
    subjectIds: ['subject-rodent-001'],
    group: {
      groupPurpose: 'housing',
      housingUnitId: 'housing-cage-a1',
      environmentalContext: {
        lightCycle: '12:12',
      },
      husbandryProtocolId: 'protocol-husbandry-rodent-standard',
      diet: 'standard chow',
      density: {
        value: 4,
        unit: 'animals/cage',
      },
      membershipPolicy: 'dynamic',
    },
  },
  {
    id: 'batch-zebrafish-spawn-001',
    organizationId,
    kind: 'batch',
    code: 'BATCH-ZF-SPAWN-001',
    name: 'Synthetic zebrafish spawn batch',
    profileTypes: ['zebrafish_batch'],
    speciesId: zebrafishSpecies.id,
    status: 'active',
    validFrom: '2026-03-01',
    subjectIds: ['subject-zebrafish-batch-001'],
    batch: {
      originType: 'spawn',
      sourceOrganization: 'Synthetic aquatic facility',
      lineId: 'line-zebrafish-synthetic-a',
      genotypeId: 'genotype-wildtype-synthetic',
      spawnDate: '2026-03-01',
      hatchDate: '2026-03-04',
      developmentalStage: 'larva',
      sexComposition: 'mixed',
      initialCount: 120,
      currentCount: 116,
      countUnit: 'larvae',
      splitMergeEventIds: ['event-mortality-zebrafish-1'],
    },
  },
  {
    id: 'group-zebrafish-tank-z1',
    organizationId,
    kind: 'group',
    code: 'GROUP-ZF-TANK-Z1',
    name: 'Synthetic zebrafish tank group Z1',
    profileTypes: ['zebrafish_batch'],
    speciesId: zebrafishSpecies.id,
    status: 'active',
    validFrom: '2026-03-01',
    subjectIds: ['subject-zebrafish-batch-001'],
    group: {
      groupPurpose: 'housing',
      housingUnitId: 'housing-tank-z1',
      environmentalContext: {
        waterTemperatureC: 27.5,
        photoperiod: '14:10',
      },
      husbandryProtocolId: 'protocol-husbandry-zebrafish-standard',
      density: {
        value: 10,
        unit: 'larvae/liter',
      },
      membershipPolicy: 'event_derived',
    },
  },
  {
    id: 'cohort-synthetic-mixed',
    organizationId,
    kind: 'cohort',
    code: 'COHORT-SYN-MIXED',
    name: 'Synthetic mixed subject cohort',
    description: 'Development cohort linking non-human synthetic subjects.',
    profileTypes: ['rodent', 'zebrafish_batch'],
    status: 'active',
    validFrom: '2026-03-01',
    subjectIds: ['subject-rodent-001', 'subject-zebrafish-batch-001'],
    cohort: {
      cohortKind: 'interventional_arm',
      studyId: 'study-synthetic-001',
      inclusionCriteria: ['Active non-human synthetic subject'],
      exclusionCriteria: ['Archived or depleted subject'],
      intervention: 'Synthetic standard observation workflow',
      randomizationMethod: 'Synthetic block allocation',
      randomizationUnit: 'subject',
      blinding: 'assessor_blinded',
      plannedSize: 2,
      followUpSchedule: ['daily welfare review', 'weekly facility review'],
    },
  },
  {
    id: 'batch-farm-birth-lot-001',
    organizationId,
    kind: 'batch',
    code: 'BATCH-FARM-BIRTH-001',
    name: 'Synthetic farm animal birth lot',
    profileTypes: ['farm_animal'],
    speciesId: cattleSpecies.id,
    status: 'active',
    validFrom: '2026-01-12',
    subjectIds: ['subject-farm-001'],
    batch: {
      originType: 'birth_lot',
      birthDate: '2026-01-12',
      sexComposition: 'mixed',
      initialCount: 8,
      currentCount: 8,
      countUnit: 'animals',
    },
  },
  {
    id: 'group-farm-herd-a',
    organizationId,
    kind: 'group',
    code: 'GROUP-FARM-HERD-A',
    name: 'Synthetic farm herd A',
    profileTypes: ['farm_animal'],
    speciesId: cattleSpecies.id,
    status: 'active',
    validFrom: '2026-01-12',
    subjectIds: ['subject-farm-001'],
    group: {
      groupPurpose: 'management',
      housingUnitId: 'housing-pasture-f1',
      environmentalContext: {
        pasture: 'synthetic pasture f1',
      },
      diet: 'pasture plus synthetic supplement',
      membershipPolicy: 'dynamic',
    },
  },
  {
    id: 'batch-generic-culture-lot-001',
    organizationId,
    kind: 'batch',
    code: 'BATCH-GEN-CULTURE-001',
    name: 'Synthetic generic culture lot',
    profileTypes: ['generic'],
    status: 'active',
    validFrom: '2026-04-01',
    subjectIds: ['subject-generic-001'],
    batch: {
      originType: 'culture_lot',
      sourceOrganization: 'Synthetic biobank',
      arrivalDate: '2026-04-01',
      initialCount: 3,
      currentCount: 3,
      countUnit: 'cultures',
    },
    metadata: {
      biologicalType: 'cell culture',
      passage: 3,
    },
  },
  {
    id: 'cohort-generic-analysis-001',
    organizationId,
    kind: 'cohort',
    code: 'COHORT-GEN-ANALYSIS-001',
    name: 'Synthetic generic analysis set',
    profileTypes: ['generic'],
    status: 'active',
    validFrom: '2026-04-01',
    subjectIds: ['subject-generic-001'],
    cohort: {
      cohortKind: 'analysis_set',
      studyId: 'study-synthetic-001',
      inclusionCriteria: ['Synthetic cell culture fixture'],
      exclusionCriteria: ['Failed quality control'],
      plannedSize: 1,
      followUpSchedule: ['analysis export'],
    },
  },
].map((aggregate) => subjectAggregateSchema.parse(aggregate)) satisfies SubjectAggregate[];

export const subjectAggregateMembershipFixtures = [
  {
    subjectId: 'subject-human-pseudo-001',
    aggregateId: 'cohort-human-observational-001',
    aggregateKind: 'cohort',
    aggregateCode: 'COHORT-HUM-OBS-001',
    aggregateName: 'Synthetic pseudonymized human observational cohort',
    role: 'analysis_member',
    validFrom: '2026-01-01',
  },
  {
    subjectId: 'subject-rodent-001',
    aggregateId: 'batch-rodent-shipment-001',
    aggregateKind: 'batch',
    aggregateCode: 'BATCH-ROD-SHIP-001',
    aggregateName: 'Synthetic rodent shipment batch',
    role: 'source',
    validFrom: '2026-02-15',
    count: 1,
  },
  {
    subjectId: 'subject-rodent-001',
    aggregateId: 'group-rodent-cage-a1',
    aggregateKind: 'group',
    aggregateCode: 'GROUP-ROD-CAGE-A1',
    aggregateName: 'Synthetic rodent cage group A1',
    role: 'housing_member',
    validFrom: '2026-02-16',
  },
  {
    subjectId: 'subject-rodent-001',
    aggregateId: 'cohort-synthetic-mixed',
    aggregateKind: 'cohort',
    aggregateCode: 'COHORT-SYN-MIXED',
    aggregateName: 'Synthetic mixed subject cohort',
    role: 'randomized_unit',
    validFrom: '2026-03-01',
  },
  {
    subjectId: 'subject-zebrafish-batch-001',
    aggregateId: 'batch-zebrafish-spawn-001',
    aggregateKind: 'batch',
    aggregateCode: 'BATCH-ZF-SPAWN-001',
    aggregateName: 'Synthetic zebrafish spawn batch',
    role: 'source',
    validFrom: '2026-03-01',
    count: 116,
  },
  {
    subjectId: 'subject-zebrafish-batch-001',
    aggregateId: 'group-zebrafish-tank-z1',
    aggregateKind: 'group',
    aggregateCode: 'GROUP-ZF-TANK-Z1',
    aggregateName: 'Synthetic zebrafish tank group Z1',
    role: 'housing_member',
    validFrom: '2026-03-01',
    count: 116,
  },
  {
    subjectId: 'subject-zebrafish-batch-001',
    aggregateId: 'cohort-synthetic-mixed',
    aggregateKind: 'cohort',
    aggregateCode: 'COHORT-SYN-MIXED',
    aggregateName: 'Synthetic mixed subject cohort',
    role: 'randomized_unit',
    validFrom: '2026-03-01',
    count: 116,
  },
  {
    subjectId: 'subject-farm-001',
    aggregateId: 'batch-farm-birth-lot-001',
    aggregateKind: 'batch',
    aggregateCode: 'BATCH-FARM-BIRTH-001',
    aggregateName: 'Synthetic farm animal birth lot',
    role: 'source',
    validFrom: '2026-01-12',
    count: 1,
  },
  {
    subjectId: 'subject-farm-001',
    aggregateId: 'group-farm-herd-a',
    aggregateKind: 'group',
    aggregateCode: 'GROUP-FARM-HERD-A',
    aggregateName: 'Synthetic farm herd A',
    role: 'member',
    validFrom: '2026-01-12',
  },
  {
    subjectId: 'subject-generic-001',
    aggregateId: 'batch-generic-culture-lot-001',
    aggregateKind: 'batch',
    aggregateCode: 'BATCH-GEN-CULTURE-001',
    aggregateName: 'Synthetic generic culture lot',
    role: 'source',
    validFrom: '2026-04-01',
    count: 1,
  },
  {
    subjectId: 'subject-generic-001',
    aggregateId: 'cohort-generic-analysis-001',
    aggregateKind: 'cohort',
    aggregateCode: 'COHORT-GEN-ANALYSIS-001',
    aggregateName: 'Synthetic generic analysis set',
    role: 'analysis_member',
    validFrom: '2026-04-01',
  },
].map((membership) =>
  subjectAggregateMembershipSchema.parse(membership),
) satisfies SubjectAggregateMembership[];

function aggregateMembershipsFor(subjectId: string): SubjectAggregateMembership[] {
  return subjectAggregateMembershipFixtures.filter(
    (membership) => membership.subjectId === subjectId,
  );
}

export const subjectFixtures = [
  {
    id: 'subject-human-pseudo-001',
    organizationId,
    subjectCode: 'HUM-PSEUDO-001',
    profileType: 'human',
    status: 'active',
    aggregateMemberships: aggregateMembershipsFor('subject-human-pseudo-001'),
    profile: {
      profileType: 'human',
      pseudonymizedSubjectCode: 'HUM-PSEUDO-001',
      consentStatus: 'consented',
      studyParticipationStatus: 'enrolled',
      ageBand: '40-49',
      sex: 'not_recorded',
      genderIdentity: 'prefer_not_to_say',
    },
  },
  {
    id: 'subject-rodent-001',
    organizationId,
    subjectCode: 'ROD-SYN-001',
    profileType: 'rodent',
    status: 'active',
    speciesId: mouseSpecies.id,
    cohortId: 'cohort-synthetic-mixed',
    aggregateMemberships: aggregateMembershipsFor('subject-rodent-001'),
    profile: {
      profileType: 'rodent',
      species: mouseSpecies,
      strainId: 'strain-mouse-synthetic-a',
      genotypeId: 'genotype-wildtype-synthetic',
      sex: 'female',
      ageDays: 84,
      housingUnitId: 'housing-cage-a1',
      welfareStatus: 'normal',
    },
  },
  {
    id: 'subject-zebrafish-batch-001',
    organizationId,
    subjectCode: 'ZFB-SYN-001',
    profileType: 'zebrafish_batch',
    status: 'active',
    speciesId: zebrafishSpecies.id,
    cohortId: 'cohort-synthetic-mixed',
    aggregateMemberships: aggregateMembershipsFor('subject-zebrafish-batch-001'),
    profile: {
      profileType: 'zebrafish_batch',
      species: zebrafishSpecies,
      batchIdentifier: 'ZFB-SYN-001',
      developmentalStage: 'larva',
      tankId: 'housing-tank-z1',
      count: 120,
      mortalityEventIds: [],
      environmentalObservationIds: [],
    },
  },
  {
    id: 'subject-farm-001',
    organizationId,
    subjectCode: 'FARM-SYN-001',
    profileType: 'farm_animal',
    status: 'active',
    speciesId: cattleSpecies.id,
    aggregateMemberships: aggregateMembershipsFor('subject-farm-001'),
    profile: {
      profileType: 'farm_animal',
      species: cattleSpecies,
      groupIdentifier: 'herd-synthetic-a',
      individualIdentifier: 'farm-synthetic-001',
      ageDescription: 'juvenile',
      sex: 'female',
      housingUnitId: 'housing-pasture-f1',
      welfareStatus: 'normal',
    },
  },
  {
    id: 'subject-generic-001',
    organizationId,
    subjectCode: 'GEN-SYN-001',
    profileType: 'generic',
    status: 'active',
    aggregateMemberships: aggregateMembershipsFor('subject-generic-001'),
    profile: {
      profileType: 'generic',
      biologicalType: 'cell culture',
      metadata: {
        fixture: true,
        passage: 3,
      },
      extensibilityNotes: 'Synthetic generic subject metadata for API fixtures.',
    },
  },
].map((subject) => subjectWithProfileSchema.parse(subject)) satisfies SubjectWithProfile[];
